[webservers]
managed01 ansible_host=20.189.95.79 ansible_user=azureuser
managed02 ansible_host=20.219.133.235 ansible_user=azureuser
[webservers:var]
ansible_ssh_private_key_file=/home/azureuser/.ssh/ed25519